name: PKConnector
version: 0.6.1
author: Viktoracri
website: https://acri.dev
main: dev.acri.pkconnector.bukkit.Main

commands:
  togglechatg:
    description: Toggle whether or not you see the global chat.
  gmsg:
    description: Message players globally
  chat:
    description: Set your current chat channel
  cg:
    description: Chat global
  cn:
    description: Chat normal
  cs:
    description: Chat staff
  cv:
    description: Chat veteran
  gr:
    description: Reply to a message globally
  findplayer:
    description: Find a player
    aliases: find
  pklist:
    description: List players globally
  pkconnector:
    description: Admin commands