name: PKConnector
version: 0.11.3.1
author: Viktoracri
website: https://acri.dev
main: dev.acri.pkconnector.bukkit.Main

commands:
  togglechatg:
    description: Toggle whether or not you see the global chat.
  gmsg:
    description: Message players globally
  pkchat:
    description: Set your current chat channel
    aliases: chat
  cg:
    description: Chat in the global chat channel
  cn:
    description: Chat normally
  cs:
    description: Chat in the staff chat channel
  cv:
    description: Chat in the veteran chat channel
  gr:
    description: Reply to a message globally
  findplayer:
    description: Find a player
    aliases: find
  pklist:
    description: List players globally
  pkconnector:
    description: Admin commands
  pkservers:
    description: Show servers currently connected to PKConnector
  togglegmsg:
    description: Toggle global private messages
  pkip:
    description: Get the public IP address of a parkour server
  pkdiscord:
    description: Get an invite to the pk community discord
  pkignore:
    description: Ignore a player across all parkour servers